export type stack =
  | "ReactJS"
  | "Tailwind"
  | "Redux"
  | "TypeScript"
  | "NextJs"
  | "NodeJS"
  | "Angular"
  | "Styled Components"
  | "SOLID"
  | "Scrum"
  | "Metodologias Agéis"
  | "MongoDb"
  | "Code Review"
  | "ColdFusion"
  | "MySql"
  | "HTML5"
  | "CSS3"
  | "JQuery"
  | "COBOL"
  | "React Native";
