import { Experience } from "./types";

export const experiencesMocked: Experience[] = [
  {
    company: "InnovaUp",
    role: {
      en: "Intern",
      pt: "Estagiário",
    },
    description: {
      en: "Responsible for N1 customer service, I developed a ticket system where customers could describe their issues, capture their screen and send to support.",
      pt: "Responsável por atender o cliente N1, desenvolvi um sistema de abertura de chamado, onde o cliente pode descrever sua dúvida, capturava a tela e envia para o suporte.",
    },
    startDate: new Date("2015-01-01"),
    finalDate: new Date("2016-01-01"),
    stack: ["Delphi"],
    projects: [],
    contractType: "Estagio",
    workmode: "Presencial",
    city: "Salvador",
  },

  {
    company: "Capgemini",
    role: {
      en: "Mid-Level Developer",
      pt: "Desenvolvedor Pleno",
    },
    description: {
      en: "Working with code analysis to update systems generated by a codemaker to a more current COBOL version.",
      pt: "Atuando com análise de código para atualização de sistemas gerados por um codemaker para uma versão de COBOL mais atual.",
    },
    startDate: new Date("2016-02-01"),
    finalDate: new Date("2019-02-01"),
    stack: ["COBOL", "Scrum", "Kanban", "Agile Methodologies"],
    projects: [],
    contractType: "CLT",
    workmode: "Presencial",
    city: "Salvador",
  },

  {
    company: "Click Interativo",
    role: {
      en: "Full Stack Developer",
      pt: "Desenvolvedor Full Stack",
    },
    description: {
      en: "Development focused on backend with ColdFusion and MySQL, also participating in frontend with JavaScript and jQuery. Responsible for creating new systems, including database modeling, architecture, API development and interfaces. I worked on complete project planning, from conception to delivery. One of the main challenges was constant project changes, sometimes working on more than one project simultaneously.",
      pt: "Desenvolvimento focado no backend com ColdFusion e MySQL, participando também do frontend com JavaScript e jQuery. Responsável pela criação de novos sistemas, incluindo modelagem de banco de dados, arquitetura, desenvolvimento de APIs e interfaces. Atuei no planejamento completo dos projetos, desde a concepção até a entrega. Sendo um dos principais desafios a constante mudança de projetos, às vezes atuando em mais de um projeto ao mesmo tempo.",
    },
    startDate: new Date("2019-08-01"),
    finalDate: new Date("2021-07-01"),
    stack: [
      "ColdFusion",
      "MySql",
      "Javascript",
      "HTML5",
      "CSS3",
      "JQuery",
    ],
    projects: [
      {
        title: {
          en: "Reveillon Gran Hotel Stella Maris",
          pt: "Reveillon Gran Hotel Stella Maris",
        },
        description: {
          en: "Ticket purchase and entry management system for New Year's Eve, requested less than 1 month before the event. The existing system had hundreds of problems the previous year, and it was necessary to refactor all code. I reduced errors to 0 and optimized the system to prevent duplicate entries.",
          pt: "Sistema de compra de ingressos e gerenciamento de entradas para o réveillon, solicitado a menos de 1 mês para a realização do evento. O sistema existente tinha dado centenas de problemas no ano anterior, e foi necessário refatorar todo o código. Reduzi a 0 a quantidade de erros e otimizei o sistema para evitar a duplicação de entradas.",
        },
      },
      {
        title: {
          en: "Cejas Online",
          pt: "Cejas Online",
        },
        description: {
          en: "E-commerce for legal courses with online classes, including student management, certificate issuance and class management.",
          pt: "E-commerce de cursos jurídicos com aulas online, com gerenciamento de alunos, emissão de certificados e gerenciamento de aulas.",
        },
      },
      {
        title: {
          en: "B&A Real Estate",
          pt: "B&A Imóveis",
        },
        description: {
          en: "Real estate website with lead and demand management. The biggest challenge was constant requirement changes and the need to keep the system updated with new business rules.",
          pt: "Site imobiliário com gerenciamento de leads e demanda. O maior desafio foi a constante mudança de requisitos e a necessidade de manter o sistema atualizado com as novas regras de negócio.",
        },
      },
      {
        title: {
          en: "Labchecap",
          pt: "Labchecap",
        },
        description: {
          en: "Institutional website for a large clinical laboratory network, including development of an integrated system for viewing exam results online, with secure authentication and intuitive interface for patients and doctors.",
          pt: "Site institucional para uma grande rede de laboratórios clínicos, incluindo desenvolvimento de sistema integrado para visualização de resultados de exames online, com autenticação segura e interface intuitiva para pacientes e médicos.",
        },
      },
      {
        title: {
          en: "Other projects",
          pt: "Outros projetos",
        },
        description: {
          en: "Shopping Bela Vista, Faculdade SantaCasa, AlphaOnfit, Labchecap, Academia Alpha, Academia Hammer, Mosello Lima",
          pt: "Shopping Bela Vista, Faculdade SantaCasa, AlphaOnfit, Labchecap, Academia Alpha, Academia Hammer, Mosello Lima",
        },
      },
    ],
    contractType: "CLT",
    workmode: "Presencial",
    city: "Salvador",
  },

  {
    company: "Supera Inovação",
    role: {
      en: "Frontend Developer",
      pt: "Desenvolvedor Front-end",
    },
    description: {
      en: "The biggest challenge was the diversity of stack, legacy systems and constant project changes. As the most experienced developer on the team, I had the opportunity to assist the rest of the team with questions and difficulties. Constantly challenged by my leader by being placed on the most complex projects.",
      pt: "Sendo o maior desafio a diversidade de stack, sistemas legados e mudança de projeto constantes. Além de ser o desenvolvedor mais experiente da equipe, tive a oportunidade de auxiliar o restante da equipe com dúvidas e dificuldades. Constantemente desafiado por meu líder, ao me colocar nos projetos mais complexos.",
    },
    startDate: new Date("2021-08-01"),
    finalDate: new Date("2022-01-01"),
    stack: [
      "React.JS",
      "NodeJS",
      "React Native",
      "Typescript",
      "Next.JS",
      "ChakraUI",
      "Tailwind",
      "Styled Components",
      "Strapi",
      "MongoDB",
      "Git",
      "GitLab",
      "Scrum",
      "Kanban",
      "Agile Methodologies",
    ],
    projects: [
      {
        title: {
          en: "Algar",
          pt: "Algar",
        },
        description: {
          en: "Adjustments to class-based React application.",
          pt: "Ajustes em aplicativo em React com classes.",
        },
      },
      {
        title: {
          en: "Bristom",
          pt: "Bristom",
        },
        description: {
          en: "Refactoring class functions to hooks, plus implementing some screens.",
          pt: "Refatoração de funções de classes para hooks, além da implementação de algumas telas.",
        },
      },
      {
        title: {
          en: "Other projects",
          pt: "Outros projetos",
        },
        description: {
          en: "GetJus, Sapcana, Daexe, Liver Web, Liver Mobile",
          pt: "GetJus, Sapcana, Daexe, Liver Web, Liver Mobile",
        },
      },
    ],
    contractType: "CLT",
    workmode: "Remoto",
  },

  {
    company: "W3block.io",
    role: {
      en: "Mid-Level Frontend Developer",
      pt: "Desenvolvedor Front-end Pleno",
    },
    description: {
      en: "Using Typescript, Tailwind, Next.JS, React.JS, Styled Components. Agile methodologies. Git for versioning.",
      pt: "Utilizando Typescript, Tailwind, Next.JS, React.JS, Styled Components. Metodologias ágeis. Git para versionamento.",
    },
    startDate: new Date("2022-02-01"),
    finalDate: new Date("2022-12-01"),
    stack: [
      "React.JS",
      "Typescript",
      "Next.JS",
      "Tailwind",
      "Git",
      "GitHub",
      "Scrum",
      "Kanban",
      "Agile Methodologies",
    ],
    projects: [
      {
        title: {
          en: "Eventix",
          pt: "Eventix",
        },
        description: {
          en: "Ticketing System",
          pt: "Ticketeria",
        },
      },
      {
        title: {
          en: "Foodburster",
          pt: "Foodburster",
        },
        description: {
          en: "Benefits Club",
          pt: "Clube de Benefícios",
        },
      },
      {
        title: {
          en: "SDK",
          pt: "SDK",
        },
        description: {
          en: "Implementation of new features",
          pt: "Implementação de novas features",
        },
      },
    ],
    contractType: "PJ",
    workmode: "Remoto",
  },

  {
    company: "Hiperbanco",
    role: {
      en: "React Developer",
      pt: "Desenvolvedor React",
    },
    description: {
      en: "Using Typescript, MaterialUI, React.JS. Agile methodologies. Git for versioning.",
      pt: "Utilizando Typescript, MaterialUI, React.JS. Metodologias ágeis. Git para versionamento.",
    },
    startDate: new Date("2023-04-01"),
    finalDate: new Date("2023-09-01"),
    stack: [
      "React.JS",
      "Typescript",
      "ChakraUI",
      "Git",
      "GitHub",
      "Scrum",
      "Kanban",
    ],
    projects: [
      {
        title: {
          en: "Internet Banking",
          pt: "Internet Banking",
        },
        description: {
          en: "Replaced Metronic with Vite, performed a complete update, restructured the project, fixed bugs and implemented the complete payroll section.",
          pt: "Substituí o Metronic pelo Vite, efetuei uma atualização completa, reestruturei o projeto, corrigi erros e implementei a seção completa de folha de pagamento.",
        },
      },
      {
        title: {
          en: "Credit as a Service",
          pt: "Credit as a Service",
        },
        description: {
          en: "Online credit request service.",
          pt: "Serviço de solicitação de crédito online.",
        },
      },
      {
        title: {
          en: "Geopay",
          pt: "Geopay",
        },
        description: {
          en: "Checkout service.",
          pt: "Serviço de checkout.",
        },
      },
    ],
    contractType: "PJ",
    workmode: "Hibrido",
    city: "Salvador",
  },

  {
    company: "OMP",
    role: {
      en: "Full Stack Developer",
      pt: "Desenvolvedor Full Stack",
    },
    description: {
      en: "Frontend development of a meme creation platform with generative AI, autonomous distribution and monetization system, using ReactJS, Vite, Tailwind, Redux and Shadcn. Backend development using Python with FastAPI, Firestore and Google Cloud.",
      pt: "Desenvolvimento front-end de plataforma de criação de memes com IA generativa, distribuição autônoma e sistema de monetização, utilizando ReactJS, Vite, Tailwind, Redux e Shadcn. Desenvolvimento back-end utilizando Python com FastAPI, Firestore e Google Cloud.",
    },
    startDate: new Date("2024-01-01"),
    finalDate: new Date("2025-06-11"),
    stack: [
      "Python",
      "React.JS",
      "Typescript",
      "Tailwind",
      "Shadcn",
      "Git",
      "GitHub",
      "Kanban",
    ],
    projects: [
      {
        title: {
          en: "MyMeme",
          pt: "MyMeme",
        },
        description: {
          en: "Meme creation platform with generative AI, autonomous distribution and monetization system.",
          pt: "Plataforma de criação de memes com IA generativa, distribuição autônoma e sistema de monetização.",
        },
        responsible: "Responsible for the frontend development.",
      },
      {
        title: {
          en: "PaalX",
          pt: "PaalX",
        },
        description: {
          en: "Cryptocurrency transaction platform.",
          pt: "Plataforma de transação de criptomoedas.",
        },
      },
    ],
    contractType: "PJ",
    workmode: "Remoto",
  },

  {
    company: "QIntess",
    role: {
      en: "Frontend Developer",
      pt: "Desenvolvedor Front-end",
    },
    description: {
      en: "Involved in the development and evolution of the IDEA System (Data Intelligence, Statistics, and Action), a core corporate platform for the Public Prosecutor's Office of the State of Bahia. This unified citizen service system automates legal workflows and extrajudicial management procedures, integrating directly with the courts of justice.",
      pt: "Atuação no desenvolvimento e evolução do Sistema IDEA (Inteligência de Dados, Estatísticas e Atuação), a plataforma corporativa central do Ministério Público do Estado da Bahia. O sistema unifica o atendimento ao cidadão, automatiza fluxos jurídicos e gerencia procedimentos extrajudiciais, integrando-se diretamente com tribunais de justiça.",
    },
    startDate: new Date("2026-06-01"),
    finalDate: undefined,
    stack: [
      "React.JS",
      "Typescript",
      "Styled Components",
      "Material UI",
      "Git",
      "GitLab",
    ],
    projects: [
      {
        title: {
          en: "Idea 2.0 - MPBA",
          pt: "Idea 2.0 - MPBA",
        },
        description: {
          en: "Development and evolution of the IDEA 2.0 platform for the Public Prosecutor's Office of the State of Bahia.",
          pt: "Desenvolvimento e evolução da plataforma IDEA 2.0 para o Ministério Público do Estado da Bahia.",
        },
      },
    ],
    contractType: "CLT",
    workmode: "Remoto",
  },
];